#!/usr/bin/env bash
# Description: Run Drush CLI inside the app container

set -e
source "${DIP_DIR}/commands/utils/color.sh"

msg "${YELLOW}[drush] $*${NOFORMAT}"
dip exec app "/var/www/html/vendor/bin/drush $*"
