#!/usr/bin/env bash
# Description: Run Django migrations (--make to create new, --rollback <app> <migration>)

set -e
source "${DIP_DIR}/commands/utils/color.sh"

case "$1" in
--make)
  msg "${YELLOW}[migrate] making migrations...${NOFORMAT}"
  dip exec app python manage.py makemigrations "${@:2}"
  ;;
--rollback)
  msg "${YELLOW}[migrate] rolling back...${NOFORMAT}"
  dip exec app python manage.py migrate "${@:2}"
  ;;
*)
  msg "${YELLOW}[migrate] running pending migrations...${NOFORMAT}"
  dip exec app python manage.py migrate "$@"
  ;;
esac

msg "${GREEN}[migrate] done${NOFORMAT}"
