#!/usr/bin/env bash
# Description: Run Rails CLI inside the container (rails generate, rails console, …)

set -e
source "${DIP_DIR}/commands/utils/color.sh"

msg "${YELLOW}[rails] $*${NOFORMAT}"
dip exec app bundle exec rails "$@"
