#!/usr/bin/env bash
# Description: Run NestJS CLI inside the container (nest generate, nest build, …)

set -e
source "${DIP_DIR}/commands/utils/color.sh"

msg "${YELLOW}[nest] $*${NOFORMAT}"
dip exec app node_modules/.bin/nest "$@"
